# Nixpacks.toml - Place this file in your project root directory

# Setup phase - specify which Nix packages to include
[phases.setup]
nixPkgs = ["nodejs", "python311"]  # Include both Node.js and Python 3.11

# Install phase - commands to run during installation
[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]  # Install Python dependencies

# Start phase - explicitly tell Nixpacks how to start the application
[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"  # Command to start the server

# Optional: Define environment variables if needed
# [variables]
# PORT = "8000"  # This is usually set by Railway automatically